### ISSUE TITLE
What about Ruby? 💎 

### ISSUE THREAD

**Issue by mculp** [Developer-DAO/pixel-avatars#55]
devastated that Ruby isn't in the language list!

Is there anything I can do to help make that happen?

**Comment by kaxel** [comment]
+1 for Ruby support

**Comment by rasmuscnielsen** [comment]
Anything in specific you guys are proposing? 😄 

So far we've tried to consolidate languages used to as few as possible just to keep it simple and accessible for the community :-) 
Also it works well since we've got free hosting on Vercel. Keeping to javascript it easy that way ❤️ 

LMK if you've got any specific proposals, otherwise I'm thinking to close this issue to keep a tidy work list

**Comment by mculp** [comment]
I would just like to be able to create an avatar with a pixelated Ruby icon. Ruby has to be more popular than Brainfuck and some of the other languages (what is Chicken?) on the list! I'm just asking for Ruby to show up in this dropdown list:

![Screenshot_20211230-025923~2](https://user-images.githubusercontent.com/129983/147737075-2d2609cb-794e-4751-ba1b-44870719343a.png)

Official icon: https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/2048px-Ruby_logo.svg.png

A pixelated version of that would be great. 

I don't understand why it would affect hosting, but I also don't know how the language list is was chosen.

**Comment by rasmuscnielsen** [comment]
@mculp Right, gotcha. The traits of the NFT's were chosen by Nader back in September when he launched the original genesis NFTs. 
As they are part of the original smart contract they cannot be changed. While we *could* add more languages etc down the line, for the time being it doesn't make sense as we're only allowing minting an Avatar NFT of the same token ID and traits as the original.

Hope that make sense.

Closing for now, feel free to open later on if we look into expanding the scope of the avatar project to include new traits :-)
