### ISSUE TITLE
Auto-select initial token to mint

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/pixel-avatars#76]
## Suggestion

After user connects with wallet, most users will probably only have 1 or 2 tokens.

I'd suggest a small change: Let's auto-select the first token.

This will
- take out one manual step of having to find/select your token you want to claim - makes that a bit easier and more obvious
- will automatically show the preview of the user's token (instead of the default `1`).
- `Claim Avatar` button will also be visible and be ready to click on

So the new version would show the token pre-selected like this:

<img width="855" alt="Screen Shot 2022-01-08 at 12 37 40 PM" src="https://user-images.githubusercontent.com/139330/148659277-a7e1c853-7b05-4471-ba49-143dcb3750af.png">

Without the default token selected, the current "token picking process" seems slightly hidden: 

<img width="483" alt="Screen Shot 2022-01-08 at 12 19 49 PM" src="https://user-images.githubusercontent.com/139330/148658816-85a522e0-d3b0-4501-b3ef-e27177cbcf38.png">

## Related

- This relates to #66 too and what we should display if token is already minted.

- A nice to have could be to show tokens  in more of a preview format -- list of boxes (maybe even a preview of the token if already minted) versus a drop-down, but that's a bigger project.

**Comment by rasmuscnielsen** [comment]
Great idea @briangershon 👍 Have had similar thoughts too 

Only potential drawback is that it might be a bit confusing that the avatar changes when you log in / the dropdown loads, as the preview + personal token dropdown are interconnected. 

But maybe that is an acceptable compromise given that's what 95% of the people will want to do anyway :-) 

Feel free to take a crack at auto-selecting first token if you're up for it! 

As for the preview-avatars I think you're right it's a bit out of scope. Mainly because we don't have optimized versions of each avatar. We're loading 9 images / layers to display 1 avatar 😄
